### ISSUE TITLE
issu with the Row quote 

### ISSUE THREAD

**Issue by anisagrebi** [softcommerceltd/magento-graphcommerce-cms#8]
When we create a Row Quote in Graph commerce Page builder we have an error in the graphql response
this is the content in gc_metadata : 
![image](https://github.com/softcommerceltd/magento-graphcommerce-cms/assets/6905270/d732af7d-be52-43f1-8676-f0aa7faecca3)

`<section data-content-type="gc-row-quote" data-appearance="default" data-element="main"><div data-content-type="gc-richtext" data-appearance="default" data-element="main"><p>test</p></div></section>`

and this is the result of the query

{
  "errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 13,
          "column": 7
        }
      ],
      "path": [
        "cmsPage",
        "cmsRowContent",
        0,
        "pageLinks"
      ],
      "extensions": {
        "debugMessage": "Cannot return null for non-nullable field \"CmsRowQuote.pageLinks\"."
      }
    }
  ]
}

**Comment by softcommerceltd** [comment]
Thanks for pointing this out. 

I've made a quick test but could not replicate the error. See attached.

![Uploading Screenshot 2024-06-24 at 17.44.52.png…]()


Could you answer the following?

1. Magento version
2. Version of SoftCommerce_GraphCommerceCms extension installed
3. Version of GraphCommerceCms installed
4. How do you query a given CMS request? Do you use GraphQL app or a client locally installed with your GC react app?

Here is the test page, the data of which can be queried by the following URL
https://gc-backend.softcommerce.dev/graphql
with the following body reqeust

```
{
  cmsPage(identifier: "test-row-quote-page") {
    cmsRowContent {
      __typename
      id
      ... on CmsRowQuote {
        __typename
        id
        quote {
          raw
        }
      }
    }
  }
}
```
Is this something similar you have in your request?

**Comment by anisagrebi** [comment]
Can you past the full  body reqeust exemple please here ?
**these are the informations you need**

Magento version : **_2.4.7 p1 EE_**
Version of SoftCommerce_GraphCommerceCms extension installed : **_1.0.5_**

i'm using : Altair
this is the query 

```
`{
 cmsPage(identifier: "home") {
    identifier
    url_key
    title
    content
    content_heading
    page_layout
    meta_title
    meta_description
    meta_keywords
    cmsRowContent{
      id
      pageLinks {
        id
        asset{
          url 
        }
        description {
          raw
          html
          text
        }
        icon
        title
        url
      }
    }
  
  }
}`

```

**Comment by anisagrebi** [comment]
i have miss format the query i confirm that is working well 
thank you for your response
here is an example of the Graph Query
```
`{
  cmsPage(identifier: "home") {
    cmsRowContent {
      __typename
      id
      ... on CmsRowQuote {
        __typename
        id
        quote {
          raw
        }
      }
      ... on CmsRowLinks {
        __typename
        id
        title
        pageLinks {
          id
          title
          url
          description {
            raw
            text
            html
          }
        }
      }
      ... on CmsRowProduct {
        id
        title
        identity
        asset {
          url
        }
        pageLinks {
          id
          title
          url
          description {
            raw
            text
            html
          }
        }
      }
    }
  }
}`
```

**Comment by softcommerceltd** [comment]
Great stuff!
To make your life easier with the setup, have a look at our demo (sample data) modules which can be used to view how components are built

https://github.com/softcommerceltd/magento-graphcommerce-cms-sample-data
https://github.com/softcommerceltd/magento-graphcommerce-cms-sample-data-media

We also have a GC demo that you can use to see how pagebuilder is integrated in the template:
https://github.com/softcommerceltd/magento-graphcommerce-pwa

Let me know if you need any help
